add_newline = false
command_timeout = 1000

# user_bg / host_bg は .zshrc が jigsaw / JigsawStudio の時に差し替える
palette = "base"

format = """
╭─$username\
$hostname\
$directory\
[](fg:#076678 bg:#8f3f71)\
$git_branch\
$git_status\
[](fg:#8f3f71 bg:#665c54)\
$time\
$cmd_duration
╰─$character"""

[username]
show_always = true
style_user = "bg:user_bg fg:white"
style_root = "bg:#cc241d fg:white"
format = "[](fg:user_bg)[$user]($style)[](fg:user_bg bg:host_bg)"

[hostname]
ssh_only = false
style = "bg:host_bg fg:white"
format = "[$hostname]($style)[](fg:host_bg bg:#076678)"
trim_at = "."
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#076678 fg:white"
format = "[$path]($style)"

[git_branch]
symbol = " "
style = "bg:#8f3f71 fg:white"
format = "[$symbol$branch]($style)"

[git_status]
style = "bg:#8f3f71 fg:white"
format = "([ $all_status$ahead_behind]($style))"

[time]
disabled = false
time_format = "%y-%m-%d - %T"
style = "bg:#665c54 fg:white"
format = "[$time]($style)[](fg:#665c54)"

[character]
success_symbol = "[⠠⠵](bold green)"
error_symbol = "[⠠⠵](bold red)"

[palettes.base]
user_bg = "#af3a03"
host_bg = "#9d6a06"
